Fixes #133 Update main4 to main5, update examples for predict-eth
oceanprotocol/predict-eth pull request #134
Opened 2023-04-13 13:17 UTC by jfdelgad

Fixes #133.

Changes proposed in this PR:

Updates readmes for Predict eth-5

2023-04-14 01:20 UTC, trentmc requested changes

2023-04-14 01:20 UTC, trentmc commented on README.md
FYI I've updated the github issue to more thoroughly describe what needs to be done. Please review. It will make my other comments here more obvious:)
https://github.com/oceanprotocol/predict-eth/pull/134

And, besides my comments here, there are some other things outside of this PR that need doing, including "Update predict-eth-data sources: 5 min time intervals not 60", and "release new predict-eth library". Those are all documented in the github issue.

2023-04-14 01:20 UTC, trentmc commented on examples/end-to-end_compare-models.md
>  Then we create the prediction for the future values 1h, 2h, ... 12h. For this example, the input is the feature vector corresponding to the latest observed data point:
Change "1h, 2h, ... 12h" to "5min, 10min, ..., 60min"

2023-04-14 01:20 UTC, trentmc commented on predict_eth/helpers.py
> +def target_12_unixtimes(start_dt: datetime.datetime) -> list:
Good to see the change here. But this will make the tests fail. You need to update the related tests. And then make sure all tests pass.

2023-04-19 06:48 UTC, jfdelgad commented on README.md
> -- [Predict-ETH Round 4](challenges/main4.md) - predictions due Wed Apr 5, 2023. [Announcement](https://blog.oceanprotocol.com/predict-eth-4-dive-into-decentralized-data-355f2281509e)
Done

2023-04-19 06:50 UTC, jfdelgad commented on challenges/main5.md
> +start_dt = datetime.datetime.utcnow() - datetime.timedelta(minutes=120) #must be >= 12h ago; we use 24
Done

2023-04-19 06:52 UTC, jfdelgad commented on challenges/main5.md
> +cex_x = ccxt.binance().fetch_ohlcv('ETH/USDT', '1h')
Done

2023-04-19 06:53 UTC, jfdelgad commented on examples/end-to-end_compare-models.md
>  Then we create the prediction for the future values 1h, 2h, ... 12h. For this example, the input is the feature vector corresponding to the latest observed data point:
Done

2023-04-19 06:57 UTC, jfdelgad commented on predict_eth/helpers.py
> +def target_12_unixtimes(start_dt: datetime.datetime) -> list:
I am a bit confused here, the test folder does not have actually any test

2023-04-19 07:32 UTC, jfdelgad commented on README.md
Done

2023-04-19 07:42 UTC, trentmc approved these changes

2023-04-19 07:43 UTC, merged

2023-04-19 07:43 UTC, trentmc commented on predict_eth/helpers.py
> +def target_12_unixtimes(start_dt: datetime.datetime) -> list:
lol true