Emphasized connecting to mumbai before publishing asset
oceanprotocol/predict-eth pull request #147
Opened 2023-10-06 14:53 UTC by idiom-bytes

Fixes #146

2023-10-06 15:17 UTC, trentmc requested changes

2023-10-06 15:17 UTC, trentmc commented on challenges/challenge-df.md
> +# Connect to mumbai network
Do NOT have this new line here to create an Ocean instance. It should have already have been done in step 1.5. And there are more than one lines. DRY

2023-10-06 15:17 UTC, trentmc commented on challenges/challenge-df.md
> +We'll now publish the asset on Mumbai. As a result of [completing the remote setup](#14-do-ocean-remote-setup), you should be ready to go.
Modify this, to remind the reader that they did this in step 1.5.

2023-10-10 14:26 UTC, idiom-bytes commented on challenges/challenge-df.md
> +# Connect to mumbai network
Done

2023-10-10 15:08 UTC, trentmc approved these changes

2023-11-02 08:42 UTC, merged