Refactor/basic model
oceanprotocol/predict-eth pull request #16
Opened 2022-10-20 20:32 UTC by jfdelgad

Fixes # .

Changes proposed in this PR:

- Changes the demo ML model for a basic linear model 
- 
-

2022-10-21 12:20 UTC, trentmc commented
Jaime, in your PRs, please
- make the title have the # and name of issue you're fixing
- make the description have the # of the issue you're fixing

E.g. for this issue:
- title: "Fix #4: predict-eth2.md: do simple model-based prediction"
- description: "Fix #4: <rest of descr>"

2022-10-21 12:21 UTC, trentmc commented on predict-eth2.md
> +future_inputs = pd.DataFrame({"ds": tmp})
Missing an import for pandas

2022-10-21 12:24 UTC, trentmc commented on predict-eth2.md
> +tmp = [datetime.datetime.utcfromtimestamp(x) for x in target_uts]
Replace with:

``python
target_dts = to_datetimes(target_uts)
``
In general, please use the support methods at the bottom. That's what they are there for:) And they help readability.

2022-10-21 12:25 UTC, trentmc requested changes
A few small changes requested

2022-10-21 14:43 UTC, jfdelgad commented on predict-eth2.md
> +future_inputs = pd.DataFrame({"ds": tmp})
Fixed

2022-10-21 14:45 UTC, jfdelgad commented on predict-eth2.md
> +tmp = [datetime.datetime.utcfromtimestamp(x) for x in target_uts]
Fixed

2022-10-21 16:51 UTC, trentmc requested changes

2022-10-21 16:51 UTC, trentmc commented on predict-eth2.md
> +uts = [datetime.datetime.utcfromtimestamp(x) for x in allcex_uts]
> uts = [datetime.datetime.utcfromtimestamp(x) for x in allcex_uts]

Confusing. This looks like "uts" to "uts" conversion? Yet the new variable took out the "allcex_" part.

Please rename to be less confusing. And create/use support method in Appendix, in a pattern similar to others, eg. `to_unixtimes()`.

2022-10-21 16:51 UTC, trentmc commented on predict-eth2.md
> +from prophet import Prophet
To be consistent with rest of this README, please put the imports in the Appendix.

2022-10-21 16:51 UTC, trentmc commented on predict-eth2.md
> +pred_vals = result.to_numpy()
I recommend to change to a single line: 
```python
pred_vals = forecast.set_index('ds')['yhat'][-12:].to_numpy()
```

2022-10-23 08:05 UTC, jfdelgad commented on predict-eth2.md
> +from prophet import Prophet
Done

2022-10-23 08:06 UTC, jfdelgad commented on predict-eth2.md
> +uts = [datetime.datetime.utcfromtimestamp(x) for x in allcex_uts]
changed to use `to_datetimes`, new variable name `dts`

2022-10-23 08:06 UTC, jfdelgad commented on predict-eth2.md
> +pred_vals = result.to_numpy()
Done

2022-10-23 11:19 UTC, trentmc approved these changes

2022-10-26 11:42 UTC, trentmc commented
Hi @jfdelgad , given the changes to the structure of the READMEs, this PR will need to get changed heavily, such that it's one of the examples.

2022-10-27 09:52 UTC, jfdelgad commented
> Hi @jfdelgad , given the changes to the structure of the READMEs, this PR will need to get changed heavily, such that it's one of the examples.

This has been addressed, i added you as reviewer of the example. I am closing this pull request.

2022-10-27 09:52 UTC, closed without merging