Fixes #4
oceanprotocol/predict-eth pull request #25
Opened 2022-10-27 09:31 UTC by jfdelgad

Fixes #4 

Changes proposed in this PR:

- Adds an example of how to predict ETH prices 1-12 hours ahead using a linear model
- 
-

2022-10-27 17:55 UTC, trentmc requested changes
Overall, this is in good shape! In the right place, and a nice simple approach for the user to get going. My comments are just about making maintenance easier.

2022-10-27 17:55 UTC, trentmc commented on README.md
> +- [Predict ETH price 1-12 hours ahead using a Ocean data and linear models](examples/predict-eth-ocean-data-linear-models.md)
Typo: "a Ocean data" -> "Ocean data"

2022-10-27 17:55 UTC, trentmc commented on examples/predict-eth-ocean-data-linear-models.md
> +Do the steps in "Appendix: Load helper functions".
To ease maintenance, I recommend replacing all the content of the "Setup" section with:

```python
From [challenge 1](../challenges/main1.md), do:
- [x] Setup
```

2022-10-27 17:55 UTC, trentmc commented on examples/predict-eth-ocean-data-linear-models.md
> +In the Python console, copy and paste the code below:
In line with the other comment, you can remove this whole "Load helper functions" section too, since the first comment has the user loading the helper functions.

Then you'll want the pandas and prophet imports next to where you use them.

(Apologies for the changes to suggestions over time. I'm trying to balance (a) minimizing how much user has to jump around with (b) large copy-and-pastes of code. If you see ways to get the best of both, I'm all ears:)

2022-10-28 14:34 UTC, jfdelgad commented on examples/predict-eth-ocean-data-linear-models.md
> +In the Python console, copy and paste the code below:
Done

2022-10-28 14:34 UTC, jfdelgad commented on examples/predict-eth-ocean-data-linear-models.md
> +Do the steps in "Appendix: Load helper functions".
Done

2022-10-28 14:37 UTC, jfdelgad commented on README.md
> +- [Predict ETH price 1-12 hours ahead using a Ocean data and linear models](examples/predict-eth-ocean-data-linear-models.md)
Done

2022-10-28 14:55 UTC, trentmc approved these changes
Looks good. Just one small tweak left to do, then all good from my side, go ahead and merge.

Nice work:)

2022-10-28 14:55 UTC, trentmc commented on examples/predict-eth-ocean-data-linear-models.md
> +
You can remove this, it's redundant with Step 1 ("1.5 Setup in Python, for Polygon").

2022-10-28 15:33 UTC, jfdelgad commented on examples/predict-eth-ocean-data-linear-models.md
> +
Done

2022-10-28 15:34 UTC, merged