Fixes #8
oceanprotocol/predict-eth pull request #33
Opened 2022-11-09 12:23 UTC by jfdelgad

Fixes #8  .

Changes proposed in this PR:

-  Add a readme describing comparison of 4 different models (linear regression, random forest, SVR, NN) for direct prediction of 1- 12 hours ahead of the current time
- 
-

2022-11-09 22:03 UTC, trentmc requested changes

2022-11-09 22:03 UTC, trentmc commented on examples/model_example_direct_prediction.md
> +  return nmse(y_test,predicted)
As discussed: please rename from "predicted" to "yhat_test"

2022-11-10 16:50 UTC, jfdelgad commented on examples/model_example_direct_prediction.md
> +  return nmse(y_test,predicted)
Done

2022-11-10 16:50 UTC, jfdelgad commented on examples/model_example_direct_prediction.md
> +  predicted = model.predict(x_test)
Done

2022-11-10 16:50 UTC, jfdelgad commented on ideas/modeling.md
> +- [Model comparison for direct prediction 1-12 hours](../examples/model_example_direct_prediction.md)
Done

2022-11-11 11:47 UTC, trentmc commented on README.md
> +- [Model comparison for direct prediction 1-12 hours](../examples/model_example_direct_prediction.md)
Please put this in the end-to-end section.

Then, approved! (Approving now, please don't wait on me after your final tweak.)

2022-11-11 11:47 UTC, trentmc approved these changes

2022-11-11 13:38 UTC, merged