Towards ##81 Update READMEs to reflect oceanpy#1095 changes (streamlined READMEs)
oceanprotocol/predict-eth pull request #88
Opened 2023-01-13 09:46 UTC by jfdelgad

Towards #81 .

Changes proposed in this PR:

- Fixes broken links in main3
- Fixes example code in main3
- Fixes helpers.md

2023-01-13 09:59 UTC, AnaLoznianu commented on challenges/main3.md
>  Finally, ensure you've filled in your Questbook entry.
Here, we can drop a link to desights as we will not use questbook anymore

2023-01-13 10:03 UTC, AnaLoznianu commented
@jfdelgad I still have to test out the code, but I am confused by one thing. Why are we giving instructions to people to use Mumbai and not Polygon mainnet?

2023-01-13 10:20 UTC, AnaLoznianu commented on challenges/main3.md
>    - Prepare by: get AR via [a faucet](https://faucet.arweave.net/) or [buying some](https://www.google.com/search?q=buy+arweave+tokens)
In option A, I think we can direct them to Arweave directly. We have a tutorial here: https://docs.oceanprotocol.com/using-ocean-market/asset-hosting#arweave

2023-01-13 10:27 UTC, AnaLoznianu commented on challenges/main3.md
>    - Prepare by: get AR via [a faucet](https://faucet.arweave.net/) or [buying some](https://www.google.com/search?q=buy+arweave+tokens)
On the line with: "- Winners announced: within one week" - maybe we can give a link to the last announcement: https://blog.oceanprotocol.com/introducing-the-winners-of-the-eth-price-prediction-data-challenge-edition-2-6acdccb9271. So they know where results will be posted.
Please treat this as a suggestion

2023-01-13 12:15 UTC, AnaLoznianu requested changes

2023-01-13 12:15 UTC, AnaLoznianu commented on challenges/main3.md
> +ocean = create_ocean_instance("polygon-main") # change the network name if needed
If we direct participants towards mumbai(polygon-test) then the judges should work on the same network

2023-01-13 12:31 UTC, jfdelgad commented on challenges/main3.md
>    - Prepare by: get AR via [a faucet](https://faucet.arweave.net/) or [buying some](https://www.google.com/search?q=buy+arweave+tokens)
added the link to the tutorial.

2023-01-13 12:53 UTC, jfdelgad commented
> @jfdelgad I still have to test out the code, but I am confused by one thing. Why are we giving instructions to use Mumbai and not Polygon mainnet? In the end, we want the predictions available on polygon right?

Mumbai was selected to avoid issues presented in the previous challenge, that has no access to buy matic

2023-01-16 08:43 UTC, AnaLoznianu approved these changes

2023-01-16 09:52 UTC, merged